SECRET = "uazADQzVUDY2n3bHAjefkruOmTTbpjzKZdFZM3TyKdoMsUJUbUcecWmLxfoB"
API_KEY = "AAAA4CP-r7Q:APA91bHIoV8Cqa9v86F6YkBhPCIsgK_fTUcEj-eiNfbJt-GrTTaykcrkcmgT7BSorkTnBiVEqDMfc" \
          "5aFXzIPTYu2PCrIEzQ2LBbN8rXffnzKr9gNuM0L9duxOR_0L3VmelskPnqLuqoOxgIp0BV-EIOl9BbR-Ueh0A"
